version: "3"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - worker

  webhook:
    build: ./api
    command: node webhook.js
    ports:
      - "3003:3003"
    env_file:
      - .env

  worker:
    build: ./worker
    env_file:
      - .env

  sync-vendor:
    build: ./vendors
    command: node syncVendor.js
    ports:
      - "3001:3001"

  async-vendor:
    build: ./vendors
    command: node asyncVendor.js
    ports:
      - "3002:3002"
